### ISSUE TITLE
Figure out a way to add attachments 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#39] opened 2017-09-19 21:09 UTC
Ideally, we'd have a way to add attachments to some of the funded projects. These include white papers, conference slides, finding aid templates, workflows, etc. The reason why this is important is because we promised Mellon in earlier years that the registry would serve as a platform to help disseminate innovations and models from our funded projects. These can be added by the program administrator in 2018.

**Comment by nkferraiolo** [comment] 2017-09-19 21:46
We're going to promise this capability to Mellon in our final proposal, but we won't need it until 2018, when the Program Administrator has a chance to populate it.

**Comment by waynegraham** [comment] 2017-09-20 14:56
Dupe of #4

**Closed by waynegraham** 2017-09-20 14:56 UTC
