### ISSUE TITLE
Collaborating institutions 

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/hidden_collections_registry#36] opened 2017-09-19 20:44 UTC
Can we add these in for the funded projects (I'm not concerned about the unfunded projects for this)? This is something that Mellon will really care about, so it would be good to have it by the time we go live. It's OK to just do this for the 2014-2016 projects right now, since we already have the data. We can figure out how to add this data for the earlier projects later.

**Comment by nkferraiolo** [comment] 2017-09-19 21:43
Is it possible to do this by 9/22?

**Comment by waynegraham** [comment] 2017-09-20 14:16
Dupe of #20

**Closed** 2017-09-20 14:18 UTC
Labels: in progress
